// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz3hIXLf7tOdKiu72Ui_7NF9ueAhktR24',
    appId: '1:56613860206:web:cab8e4e7ccb3ec0017c77f',
    messagingSenderId: '56613860206',
    projectId: 'fast-tensor-362106',
    authDomain: 'fast-tensor-362106.firebaseapp.com',
    storageBucket: 'fast-tensor-362106.appspot.com',
    measurementId: 'G-SENL2229DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUz0huok268pvoApcucU2RfsfR8I9QlM',
    appId: '1:56613860206:android:bf808d4aa6f5339d17c77f',
    messagingSenderId: '56613860206',
    projectId: 'fast-tensor-362106',
    storageBucket: 'fast-tensor-362106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAez-Fyi44pY4OdhQ5r5LLrxXbxF9X89BA',
    appId: '1:56613860206:ios:e17ed9570f1ed93d17c77f',
    messagingSenderId: '56613860206',
    projectId: 'fast-tensor-362106',
    storageBucket: 'fast-tensor-362106.appspot.com',
    iosClientId: '56613860206-4is1dpp8upnke4ui4tdpuvb9bsplodoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleDocClone',
  );
}
